#!/bin/sh

if [ $# = 0 ]; then
    echo "Please input steps, such as ./verify b0"
    exit 0;
fi

for step in "$@"; do
    case $step in
        b0)
            make clean && make STEP=b0 run | tee /tmp/b0
            ;;
        b1)
            make clean && make STEP=b1 run | tee /tmp/b1
            ;;
            # EXTRA_ARGS=''
            # -Clink-dead-code
            # -Ccodegen-units=1
            # -Clto=thin
        *)
            echo 'no such step'
            ;;
    esac
done

